import type { Anixart } from "./anixartClient";

import { Article } from "../api/article/article";
import { ArticleComment } from "../api/article/articleComment";
import { ArticleSuggestion } from "../api/article/articleSuggestion";
import { Auth } from "../api/auth";
import { Channel } from "../api/channel";
import { Collection } from "../api/collection/collection";
import { CollectionComment } from "../api/collection/collectionComment";
import { CollectionFavorite } from "../api/collection/collectionFavorite";
import { CollectionMy } from "../api/collection/collectionMy";
import { Config } from "../api/config";
import { Discover } from "../api/discover";
import { Export } from "../api/export";
import { Feed } from "../api/feed";
import { Import } from "../api/import";
import { Notification } from "../api/notification/notification";
import { NotificationPreference } from "../api/notification/notificationPreference";
import { Profile } from "../api/profile/profile";
import { ProfileBadge } from "../api/profile/profileBadge";
import { ProfileBlockList } from "../api/profile/profileBlockList";
import { ProfileDeletion } from "../api/profile/profileDeletion";
import { ProfileFriends } from "../api/profile/profileFriend";
import { ProfileHealth } from "../api/profile/profileHealth";
import { ProfileList } from "../api/profile/profileList";
import { ProfilePreference } from "../api/profile/profilePreference";
import { ProfileReleaseVote } from "../api/profile/profileReleaseVote";
import { ProfileRoleList } from "../api/profile/profileRoleList";
import { Episode } from "../api/release/episode";
import { Favorite } from "../api/release/favorite";
import { Filter } from "../api/release/filter";
import { History } from "../api/release/history";
import { Related } from "../api/release/related";
import { Release } from "../api/release/release";
import { ReleaseComment } from "../api/release/releaseComment";
import { ReleaseStreamingPlatform } from "../api/release/releaseStreamingPlatform";
import { ReleaseVideo } from "../api/release/releaseVideo";
import { ReleaseVideoAppeal } from "../api/release/releaseVideoAppeal";
import { ReleaseVideoFavorite } from "../api/release/releaseVideoFavorite";
import { Schedule } from "../api/release/schedule";
import { Report } from "../api/report";
import { Search } from "../api/search";
import { Type } from "../api/type";

export class Endpoints {
  public readonly article: Article;
  public readonly articleComment: ArticleComment;
  public readonly articleSuggestion: ArticleSuggestion;
  public readonly auth: Auth;
  public readonly channel: Channel;
  public readonly collection: Collection;
  public readonly collectionComment: CollectionComment;
  public readonly collectionFavorite: CollectionFavorite;
  public readonly collectionMy: CollectionMy;
  public readonly config: Config;
  public readonly discover: Discover;
  public readonly export: Export;
  public readonly feed: Feed;
  public readonly import: Import;
  public readonly notification: Notification;
  public readonly notificationPreference: NotificationPreference;
  public readonly profile: Profile;
  public readonly profileBadge: ProfileBadge;
  public readonly profileBlockList: ProfileBlockList;
  public readonly profileDeletion: ProfileDeletion;
  public readonly profileFriends: ProfileFriends;
  public readonly profileHealth: ProfileHealth;
  public readonly profileList: ProfileList;
  public readonly profilePreference: ProfilePreference;
  public readonly profileReleaseVote: ProfileReleaseVote;
  public readonly profileRoleList: ProfileRoleList;
  public readonly episode: Episode;
  public readonly favorite: Favorite;
  public readonly filter: Filter;
  public readonly history: History;
  public readonly related: Related;
  public readonly release: Release;
  public readonly releaseComment: ReleaseComment;
  public readonly releaseStreamingPlatform: ReleaseStreamingPlatform;
  public readonly releaseVideo: ReleaseVideo;
  public readonly releaseVideoAppeal: ReleaseVideoAppeal;
  public readonly releaseVideoFavorite: ReleaseVideoFavorite;
  public readonly schedule: Schedule;
  public readonly report: Report;
  public readonly search: Search;
  public readonly type: Type;

  public constructor(client: Anixart) {
    this.article = new Article(client);
    this.articleComment = new ArticleComment(client);
    this.articleSuggestion = new ArticleSuggestion(client);
    this.auth = new Auth(client);
    this.channel = new Channel(client);
    this.collection = new Collection(client);
    this.collectionComment = new CollectionComment(client);
    this.collectionFavorite = new CollectionFavorite(client);
    this.collectionMy = new CollectionMy(client);
    this.config = new Config(client);
    this.discover = new Discover(client);
    this.export = new Export(client);
    this.feed = new Feed(client);
    this.import = new Import(client);
    this.notification = new Notification(client);
    this.notificationPreference = new NotificationPreference(client);
    this.profile = new Profile(client);
    this.profileBadge = new ProfileBadge(client);
    this.profileBlockList = new ProfileBlockList(client);
    this.profileDeletion = new ProfileDeletion(client);
    this.profileFriends = new ProfileFriends(client);
    this.profileHealth = new ProfileHealth(client);
    this.profileList = new ProfileList(client);
    this.profilePreference = new ProfilePreference(client);
    this.profileReleaseVote = new ProfileReleaseVote(client);
    this.profileRoleList = new ProfileRoleList(client);
    this.episode = new Episode(client);
    this.favorite = new Favorite(client);
    this.filter = new Filter(client);
    this.history = new History(client);
    this.related = new Related(client);
    this.release = new Release(client);
    this.releaseComment = new ReleaseComment(client);
    this.releaseStreamingPlatform = new ReleaseStreamingPlatform(client);
    this.releaseVideo = new ReleaseVideo(client);
    this.releaseVideoAppeal = new ReleaseVideoAppeal(client);
    this.releaseVideoFavorite = new ReleaseVideoFavorite(client);
    this.schedule = new Schedule(client);
    this.report = new Report(client);
    this.search = new Search(client);
    this.type = new Type(client);
  }
}
